#!/bin/bash

cd simulations;

# Run tests
python -m unittest discover . '*test*.py'

# # # To profile, replace the first line with:
# # # python -m cProfile -o output.txt experiment.py \"

python experiment.py  \
	--numClients 10 \
	--numServers 5 \
	--numWorkload 200 \
	--workloadModel poisson \
	--serverConcurrency 4 \
	--serviceTime 4 \
	--utilization 0.60 \
	--serviceTimeModel random.expovariate \
	--replicationFactor 3 \
	--backpressure \
	--rateInterval  20\
	--cubicC 0.000004\
	--cubicSmax 10\
	--cubicBeta 0.2\
	--hysterisisFactor 2\
	--selectionStrategy C3 \
	--shadowReadRatio 0.1 \
	--accessPattern uniform \
	--nwLatencyBase 0.2 \
	--nwLatencyMu 0.0\
	--nwLatencySigma 0.00 \
	--expPrefix 02_C3 \
	--simulationDuration 30000 \
	--seed 3 \
	--numRequests 20000\
	--logFolder logs\
	--expScenario syncTimeVaryingServiceTimeServers\
	--demandSkew 0.0\
	--highDemandFraction 0.0\
	--slowServerFraction 0.0\
	--slowServerSlowness 0.0\
	--intervalParam 500\
	--timeVaryingDrift 3\
	--concurrencyWeight 10\
	--batchSizeModel constant\
	--batchSizeParam 1;

python experiment.py  \
	--numClients 10 \
	--numServers 5 \
	--numWorkload 200 \
	--workloadModel poisson \
	--serverConcurrency 4 \
	--serviceTime 4 \
	--utilization 0.60 \
	--serviceTimeModel random.expovariate \
	--replicationFactor 3 \
	--backpressure \
	--backpressureStrategy bic \
	--rateInterval  20\
	--cubicC 0.000004\
	--cubicSmax 10\
	--cubicBeta 0.2\
	--hysterisisFactor 2\
	--selectionStrategy C3 \
	--shadowReadRatio 0.1 \
	--accessPattern uniform \
	--nwLatencyBase 0.2 \
	--nwLatencyMu 0.0\
	--nwLatencySigma 0.00 \
	--expPrefix 02_BIC \
	--simulationDuration 30000 \
	--seed 3 \
	--numRequests 20000\
	--logFolder logs\
	--expScenario syncTimeVaryingServiceTimeServers\
	--demandSkew 0.0\
	--highDemandFraction 0.0\
	--slowServerFraction 0.0\
	--slowServerSlowness 0.0\
	--intervalParam 500\
	--timeVaryingDrift 3\
	--concurrencyWeight 10\
	--batchSizeModel constant\
	--batchSizeParam 1;

python experiment.py  \
	--numClients 10 \
	--numServers 5 \
	--numWorkload 200 \
	--workloadModel poisson \
	--serverConcurrency 4 \
	--serviceTime 4 \
	--utilization 0.60 \
	--serviceTimeModel random.expovariate \
	--replicationFactor 3 \
	--backpressure \
	--backpressureStrategy pisces \
	--desiredRtt 8.0 \
	--piscesAlpha 0.1\
	--rateInterval  20\
	--cubicC 0.000004\
	--cubicSmax 10\
	--cubicBeta 0.2\
	--hysterisisFactor 2\
	--selectionStrategy C3 \
	--shadowReadRatio 0.1 \
	--accessPattern uniform \
	--nwLatencyBase 0.2 \
	--nwLatencyMu 0.0\
	--nwLatencySigma 0.00 \
	--expPrefix 02_PISC \
	--simulationDuration 30000 \
	--seed 3 \
	--numRequests 20000\
	--logFolder logs\
	--expScenario syncTimeVaryingServiceTimeServers\
	--demandSkew 0.0\
	--highDemandFraction 0.0\
	--slowServerFraction 0.0\
	--slowServerSlowness 0.0\
	--intervalParam 500\
	--timeVaryingDrift 3\
	--concurrencyWeight 10\
	--batchSizeModel constant\
	--batchSizeParam 1;

python experiment.py  \
	--numClients 10 \
	--numServers 5 \
	--numWorkload 200 \
	--workloadModel poisson \
	--serverConcurrency 4 \
	--serviceTime 4 \
	--utilization 0.60 \
	--serviceTimeModel random.expovariate \
	--replicationFactor 3 \
	--rateInterval  20\
	--cubicC 0.000004\
	--cubicSmax 10\
	--cubicBeta 0.2\
	--hysterisisFactor 2\
	--selectionStrategy C3 \
	--shadowReadRatio 0.1 \
	--accessPattern uniform \
	--nwLatencyBase 0.2 \
	--nwLatencyMu 0.0\
	--nwLatencySigma 0.00 \
	--expPrefix 02_NO_BACK \
	--simulationDuration 30000 \
	--seed 3 \
	--numRequests 20000\
	--logFolder logs\
	--expScenario syncTimeVaryingServiceTimeServers\
	--demandSkew 0.0\
	--highDemandFraction 0.0\
	--slowServerFraction 0.0\
	--slowServerSlowness 0.0\
	--intervalParam 500\
	--timeVaryingDrift 3\
	--concurrencyWeight 10\
	--batchSizeModel constant\
	--batchSizeParam 1;

cd ..
cd plotting;
# Rscript timeseries.r PRIMARY;
# Rscript timeseries.r rp;
# Rscript timeseries.r ORA;
# Rscript timeseries.r LOR;
# Rscript timeseries.r pendingXserviceTime;
Rscript timeseries.r 02_C3;
Rscript timeseries.r 02_BIC;
Rscript timeseries.r 02_PISC;
Rscript timeseries.r 02_NO_BACK;
cd ..
